/*
 * ChangePasswordFrame.java
 *
 * Created on September 18, 2000, 3:49 AM
 */
package com.esd.ui;

import com.esd.control.AuthenticationManager;
import com.esd.control.AuthenticationManagerImpl;
import com.esd.pojo.Login;
import com.esd.util.Constants;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author  Duminda
 */
public class ChangePasswordFrame extends javax.swing.JFrame {

    private String userName;
    private String password;
    private MainJFrame mainJFrame;
    private AuthenticationManager authenticationManager;

    /** Creates new form ChangePasswordFrame */
    public ChangePasswordFrame(String userName, String password, MainJFrame mainJFrame) {
        initComponents();
        System.out.println("fdsfdsffsdf "+ password);
        this.userName = userName;
        this.password = password;
        this.mainJFrame = mainJFrame;

        authenticationManager = new AuthenticationManagerImpl();

        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) dimension.getWidth();
        int height = (int) dimension.getHeight();
        setLocation(width / 4, height / 4);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        oldPwdPf = new javax.swing.JPasswordField();
        newPwdPf = new javax.swing.JPasswordField();
        confirmPwdPf = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");

        jLabel1.setText("Old Password");

        jLabel2.setText("New Password");

        jLabel3.setText("Confirm Password");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirmPwdPf)
                            .addComponent(newPwdPf)
                            .addComponent(oldPwdPf, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(oldPwdPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newPwdPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(confirmPwdPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        this.setVisible(false);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String oldPassword = new String(oldPwdPf.getPassword());

        if (oldPassword != null) {

            if (oldPassword.equals(password)) {


                String newPassword = new String(newPwdPf.getPassword());

                if (newPassword != null && newPassword.length() > 0) {

                    String confirmPassword = new String(confirmPwdPf.getPassword());

                    if (confirmPassword != null && confirmPassword.length() > 0) {

                        if (confirmPassword.equals(newPassword)) {

                            Login login = new Login();

                            login.setUsername(userName);
                            login.setPassword(confirmPassword);


                            String response = authenticationManager.changePassword(login);

                            if (response.equals(Constants.PASSWORD_CHANGED)) {

                                //   mainUIFrame.setPassword(newPassword);

                                JOptionPane.showMessageDialog(this, " Password Changed Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                                oldPwdPf.setText("");
                                newPwdPf.setText("");
                                confirmPwdPf.setText("");

                            } else {

                                JOptionPane.showMessageDialog(this, "Password did not Change", "Error", JOptionPane.ERROR_MESSAGE);
                            }

                        } else {
                            JOptionPane.showMessageDialog(this, "New Password not Equal to Confirm Password ", "Error", JOptionPane.ERROR_MESSAGE);
                            confirmPwdPf.requestFocus();
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Confirm Password can't be empty", "Error", JOptionPane.ERROR_MESSAGE);
                        confirmPwdPf.requestFocus();
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "New Password can't be empty", "Error", JOptionPane.ERROR_MESSAGE);
                    newPwdPf.requestFocus();
                }

            } else {

                JOptionPane.showMessageDialog(this, "Incorrect Existing Password", "Error", JOptionPane.ERROR_MESSAGE);
                oldPwdPf.requestFocus();
            }

        } else {

            JOptionPane.showMessageDialog(this, "Old Password can't be empty", "Error", JOptionPane.ERROR_MESSAGE);
            oldPwdPf.requestFocus();

        }




    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

        this.setVisible(false);

    }//GEN-LAST:event_jMenu1ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPwdPf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPasswordField newPwdPf;
    private javax.swing.JPasswordField oldPwdPf;
    // End of variables declaration//GEN-END:variables
}
